name: CI

on:
  push: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Global install truffle
      env: 
        NPM_CONFIG_PREFIX: ~/.npm-global
      run: | 
        sudo npm install -g truffle
        sudo npm install -g ethereumjs-testrpc
    - name: move node modules
      run: node_modules/.bin/ganache-cli --gasLimit 10000000 > /dev/null & sleep 5
    - name: prep build
      run: rm -rf build
    - name: compile
      run: truffle compile
    - name: migrate
      run: truffle migrate --reset --network development
    - name: test
      run: truffle test
